### ISSUE TITLE
User Profiles

### ISSUE THREAD

**Issue by zsediqyar** [codeclubsocial/codeclub_website_dev#22]
Now that user auth seems to be working and we are able to post data to the DB from the sign up page, just raising this issue so we can work on it.

- [x] 1. SignUp page needs a couple of more field about the user information, like name. #23
- [x] 2. After initial sign up, the user should be redirected to the user profile page #24
- [x] 3. Certain features should be blocked from user access until he/she signs up. #25
- [x] 4. Once logged in, the SIGNUP and LOGIN icon/button from the navbar should be removed and only LOG OUT should be shown. #25

**Comment by craig429** [comment]
I agree with all of this.
We need to define a profile page. Then we need to update the mongo schema to accomodate the extra fields. 
As far as site access control, we can use the method used to protect the Secret Page in the current dev branch. We can also use this to turn on/turn off irrelevant buttons, like Login, once the user is logged in.

**Comment by holaymolay** [comment]
Craig, be sure to use "comment" instead of "close and comment".

**Comment by craig429** [comment]
I keep accidentally closing stuff. Can I blame it on poor Git interface design or do I need to confront the probability of oncoming dementia?

**Comment by holaymolay** [comment]
Lol, Craig.

Ok I will bump these out into their own issues.

**Comment by holaymolay** [comment]
Alright, Zaki I edited your initial comment to clarify the components of this issue and break out sub-issues to be tackled individually

**Comment by holaymolay** [comment]
Just an update to this...

Instead of redirecting to the profile page, users should be redirected to a message that says "an email confirmation has been sent, please confirm".

**Comment by holaymolay** [comment]
zakis original todo list has been satisfied. The remaining tasks have been assigned to #50
